spring.database = POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sem2
spring.datasource.username=postgres
spring.datasource.password=7777
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect